#!/usr/bin/env python3
"""
build_extra_words.py

Finds Bangla words that the bundled autocorrect wordlist (autodict.plist) knows
but database.db3 does not, and writes them to data/extra-words.tsv for the app
to load alongside the main dictionary.

Why a separate file instead of editing database.db3:

  * A SQLite file is a binary; a 1,200-word change would be unreviewable in
    git and would conflict on every merge.
  * The gap is measured against the autocorrect wordlist, so regenerating from
    that source keeps the two in step. Run this after updating either file.

Routing: a word is placed in the table whose name is the longest prefix of its
roman spelling, so "khor" lands in KH, "matha" in M, "oikotha" in OI. The
existing tables are named by syllable onset and this reuses that vocabulary
rather than inventing a new ordering.

Usage: tools/build_extra_words.py [--check]
       --check exits non-zero if the generated file is out of date, for CI.
"""

import argparse
import os
import plistlib
import sqlite3
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Table names, longest first so the longest prefix wins.
def table_names(db):
    cur = db.execute("SELECT name FROM sqlite_master WHERE type='table'")
    names = [r[0] for r in cur.fetchall() if r[0] != "Suffix"]
    return sorted(names, key=len, reverse=True)


def is_bangla(word):
    return any("ঀ" <= ch <= "৿" for ch in word)


# Bangla letter -> table holding words with that onset. This is the reliable
# signal: the roman key often does not match the sound ("wikipedia" and "xcode"
# both start with a vowel cluster in Bangla), but the word's own first letter
# always does.
BANGLA_ONSET = {
    "অ": "A", "আ": "AA", "ই": "I", "ঈ": "II", "উ": "U", "ঊ": "UU",
    "ঋ": "RRI", "এ": "E", "ঐ": "OI", "ও": "O", "ঔ": "OU",
    "ক": "K", "খ": "KH", "গ": "G", "ঘ": "GH", "ঙ": "NGA",
    "চ": "CH", "ছ": "CH", "জ": "J", "ঝ": "JH", "ঞ": "NYA",
    "ট": "T", "ঠ": "TH", "ড": "D", "ঢ": "DH", "ণ": "N",
    "ত": "T", "থ": "TH", "দ": "D", "ধ": "DH", "ন": "N",
    "প": "P", "ফ": "PH", "ব": "B", "ভ": "BH", "ম": "M",
    "য": "Y", "র": "R", "ল": "L",
    "শ": "SH", "ষ": "SS", "স": "S", "হ": "H",
}

# Words whose onset has no matching table (a few use a "z" sound, which Bangla
# does not have). They go here, and the app searches this table for every term,
# so nothing is lost.
FALLBACK_TABLE = "EXTRA"


def route(word, roman, names):
    first = word[0]
    table = BANGLA_ONSET.get(first)
    if table and any(n.lower() == table.lower() for n in names):
        return table
    # Fall back to the longest table name that prefixes the roman spelling.
    lowered = roman.lower()
    for name in names:
        if name.lower() == FALLBACK_TABLE.lower():
            continue
        if lowered.startswith(name.lower()):
            return name
    return FALLBACK_TABLE


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the generated file is stale")
    args = parser.parse_args()

    with open(os.path.join(ROOT, "autodict.plist"), "rb") as fh:
        autodict = plistlib.load(fh)

    db = sqlite3.connect(
        "file:" + os.path.join(ROOT, "database.db3") + "?mode=ro", uri=True)
    names = table_names(db)

    have = set()
    for name in names:
        for (word,) in db.execute('SELECT Words FROM "%s"' % name):
            have.add(word)

    # Bangla values the wordlist knows, with the roman spelling that produced
    # them. Values with several keys keep the shortest key: that is the form a
    # user is most likely to type.
    roman_for = {}
    for roman, value in autodict.items():
        if not value or not is_bangla(value):
            continue
        if value in have:
            continue
        # URL/TLD fragments such as ".com" are AutoCorrect material, not
        # dictionary words, and would suggest oddly in normal text.
        if value.startswith("."):
            continue
        if value in roman_for:
            if len(roman) < len(roman_for[value]):
                roman_for[value] = roman
        else:
            roman_for[value] = roman

    routed = {}
    fallback = []
    for word, roman in sorted(roman_for.items()):
        table = route(word, roman, names)
        if table == FALLBACK_TABLE:
            fallback.append((word, roman))
        routed.setdefault(table, set()).add(word)

    out_path = os.path.join(ROOT, "data", "extra-words.tsv")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    lines = [
        "# Bangla words present in autodict.plist but missing from database.db3.",
        "# Generated by tools/build_extra_words.py - do not edit by hand.",
        "# Format: TABLE<TAB>WORD",
    ]
    total = 0
    for table in sorted(routed):
        for word in sorted(routed[table]):
            lines.append("%s\t%s" % (table, word))
            total += 1
    content = "\n".join(lines) + "\n"

    if args.check:
        existing = ""
        if os.path.exists(out_path):
            with open(out_path, encoding="utf-8") as fh:
                existing = fh.read()
        if existing != content:
            print("data/extra-words.tsv is out of date; "
                  "run tools/build_extra_words.py", file=sys.stderr)
            return 1
        print("data/extra-words.tsv is up to date (%d words)" % total)
        return 0

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    print("wrote %d words across %d tables to %s"
          % (total, len(routed), os.path.relpath(out_path, ROOT)))
    if fallback:
        print("%d word(s) had no matching table and went to %s:"
              % (len(fallback), FALLBACK_TABLE))
        for word, roman in fallback[:20]:
            print("  %s  (roman: %s)" % (word, roman))
    return 0


if __name__ == "__main__":
    sys.exit(main())
